### ISSUE TITLE
Error when downloading shapefile

### ISSUE THREAD

**Issue by patadv** [haoliangyu/boundary.now#2] opened 2017-07-13 17:30 UTC
When attempting to download the shapefile of any location, I get these errors in the console: 

app.944c5b3….bundle.js:87 Error: This method has been removed in JSZip 3.0, please check the upgrade guide.
    at y (app.944c5b3….bundle.js:40)
    at r.generate (app.944c5b3….bundle.js:270)
    at t.exports (app.944c5b3….bundle.js:264)
    at Object.t.exports [as download] (app.944c5b3….bundle.js:264)
    at t.downloadShapefile (app.944c5b3….bundle.js:259)
    at View_t3.handleEvent_19 (/t/t/component.ngfactory.js:334)
    at HTMLButtonElement.<anonymous> (app.944c5b3….bundle.js:151)
    at t.invokeTask (app.944c5b3….bundle.js:40)
    at Object.onInvokeTask (app.944c5b3….bundle.js:87)
    at t.invokeTask (app.944c5b3….bundle.js:40)
    at n.runTask (app.944c5b3….bundle.js:40)
    at HTMLButtonElement.invoke (app.944c5b3….bundle.js:40)
t.handleError @ app.944c5b3….bundle.js:87
next @ app.944c5b3….bundle.js:88
e.object.i @ app.944c5b3….bundle.js:87
e.__tryOrUnsub @ app.944c5b3….bundle.js:90
e.next @ app.944c5b3….bundle.js:90
e._next @ app.944c5b3….bundle.js:90
e.next @ app.944c5b3….bundle.js:90
e.next @ app.944c5b3….bundle.js:90
e.emit @ app.944c5b3….bundle.js:87
t.triggerError @ app.944c5b3….bundle.js:87
onHandleError @ app.944c5b3….bundle.js:87
t.handleError @ app.944c5b3….bundle.js:40
n.runTask @ app.944c5b3….bundle.js:40
invoke @ app.944c5b3….bundle.js:40
app.944c5b3….bundle.js:90 Uncaught y {__zone_symbol__error: Error: This method has been removed in JSZip 3.0, please check the upgrade guide.
    at y (https://……}

**Comment by haoliangyu** [comment] 2017-07-15 03:01
@patadv Thanks for reporting this issue. The bug is caused by a broken dependency function. After updating the dependency, it is now fixed and the shapefile is downloadable again.

**Closed by haoliangyu** 2017-07-15 03:01 UTC
